name: cshop
version: 0.1.0
main: castro.cshop.Plugin
depend: [Vault, Base_cPlugin, cWorlds]
commands:
  cshop:
  buy:
    description: 
    aliases: [kup]
    usage: /<command> <item> [extra info] [time]